url: https://tombinnscodes.github.io
baseurl:

# Site settings
title: Tom Binns, MSci
email: tombinnscodes@gmail.com
description: "Freelance software engineer and research scientist specialising in machine learning, signal processing, and statistics."


# Team names, titles and social links
people:
- name: Tom Binns
  pic: 1
  social:
    - title: github
      url: https://github.com/tsbinns
    - title: envelope  # email
      url: mailto:tombinnscodes@gmail.com

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/tsbinns
  - title: envelope  # email
    url: mailto:tombinnscodes@gmail.com

# Postal address (add as many lines as necessary)
address:

# Build settings
markdown: kramdown
permalink: pretty